# Single node cluster setup
# (see https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/SingleCluster.html)
- name: Install requirements
  become: true
  ansible.builtin.apt:
    name:
      - ssh          # used for managing Hadoop daemons
      - pdsh         # improved ssh resource management
      - default-jdk  # Java Development Kit required by Hadoop

- ansible.builtin.import_tasks: hadoop.yml
  when: hadoop_version != _current_hadoop_version

- name: Install Bash config
  ansible.builtin.template: src=hadoop.bashrc dest=~/.bashrc.d/

- name: Set GitHub Actions environment
  ansible.builtin.shell: |
    echo "HADOOP_HOME={{ _hadoop_home }}" >> $GITHUB_ENV
    echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+${LD_LIBRARY_PATH}:}{{ _hadoop_ld_lib_dir }}" \
          >> $GITHUB_ENV
    echo "SPARK_DIST_CLASSPATH=$(\"{{ _hadoop_home }}/bin/hadoop\" classpath)" >> $GITHUB_ENV
    echo "SPARK_LOCAL_IP=127.0.0.1" >> $GITHUB_ENV
  when: _github_actions

- name: Install Google Cloud Storage connector
  become: true
  ansible.builtin.get_url:
    url: '{{ _hadoop_gcs_endpoint }}/{{ _hadoop_gcs_jar_file }}'
    dest: '{{ _hadoop_lib_dir }}/{{ _hadoop_gcs_jar_file }}'
  when: hadoop_gcs_connector_version

- name: Install AWS module
  become: true
  ansible.builtin.get_url:
    url: '{{ _hadoop_aws_endpoint }}/{{ hadoop_aws_version }}/{{ _hadoop_aws_jar_file }}'
    dest: '{{ _hadoop_lib_dir }}/{{ _hadoop_aws_jar_file }}'
  when: hadoop_aws_version

- name: Install AWS Java SDK
  become: true
  ansible.builtin.get_url:
    url: "{{ _hadoop_aws_java_sdk_endpoint }}/{{ hadoop_aws_java_sdk_version }}/\
          {{ _hadoop_aws_java_sdk_jar_file }}"
    dest: '{{ _hadoop_lib_dir }}/{{ _hadoop_aws_java_sdk_jar_file }}'
  when: hadoop_aws_java_sdk_version
