_chromedriver_domain: https://chromedriver.storage.googleapis.com
_chrome_main_version: '{{
  lookup("ansible.builtin.pipe", "google-chrome --version")|regex_search("([0-9]+\.?){2}[0-9]+")
}}'
_chromedriver_version: '{{
  lookup(
    "ansible.builtin.url",
    "{{ _chromedriver_domain }}/LATEST_RELEASE_{{ _chrome_main_version }}",
  )
}}'
_current_chromedriver_version: '{{
  lookup("ansible.builtin.pipe", "chromedriver --version 2>/dev/null || echo none")
  |regex_search("[0-9.]+")
}}'
