- hosts: localhost
  tags: never
  roles:
    # Cloud infrastructure
    - {role: terraform, tags: terraform}
    - {role: aws, tags: aws}
    - {role: gcp, tags: gcp}
    # Browser automation
    - {role: chrome, tags: chrome}
    - {role: chromedriver, tags: chromedriver}
    # Shells
    - {role: fish, tags: fish}
    # Data processing
    - {role: hadoop, tags: hadoop}
