- hosts: localhost
  tags: never
  roles:
    - {role: chrome, tags: chrome}
    - {role: chromedriver, tags: chromedriver}
    - {role: hadoop, tags: hadoop}
    - {role: terraform, tags: terraform}
