- hosts: localhost
  tags: never
  roles:
    # Cloud infrastructure
    - {role: terraform, tags: terraform}
    - {role: aws, tags: aws}
    - {role: gcp, tags: gcp}
    # Browsers
    - {role: chrome, tags: chrome}
    # Shells
    - {role: fish, tags: fish}
