- name: Create temporary folder
  ansible.builtin.tempfile:
    state: directory
    suffix: .chromedriver
  register: temp_dir

- name: Download ChromeDriver
  ansible.builtin.unarchive:
    src: "{{ _chromedriver_url }}"
    dest: "{{ temp_dir.path }}"
    remote_src: true

- name: Install ChromeDriver
  become: true
  ansible.builtin.copy:
    src: "{{ temp_dir.path }}/chromedriver-linux64/chromedriver"
    dest: /usr/local/bin/chromedriver
    remote_src: true
    mode: 0755
