- name: Create temporary folder
  ansible.builtin.tempfile:
    state: directory
    suffix: .chromedriver
  register: temp_dir

- name: Download ChromeDriver
  ansible.builtin.unarchive:
    src: "{{ _chromedriver_domain }}/{{ _chromedriver_version }}/chromedriver_linux64.zip"
    remote_src: true
    dest: "{{ temp_dir.path }}"

- name: Install ChromeDriver
  become: true
  ansible.builtin.copy:
    src: "{{ temp_dir.path }}/chromedriver"
    dest: /usr/local/bin/chromedriver
    remote_src: true
    mode: 0755
